### ISSUE TITLE
FastQC fails if all reads in the first tile have zero length

### ISSUE THREAD

**Issue by trachtok** [s-andrews/FastQC#57] opened 2020-08-27 15:03 UTC
Hi,
I recently encountered a problem with FastQC when running it on a fastq file created by Cutadapt (with option --too-short-output). 

```Started analysis of METSEQ-P16_SE.ad3short.fastq
Analysis complete for METSEQ-P16_SE.ad3short.fastq
Failed to process file METSEQ-P16_SE.ad3short.fastq
java.lang.IllegalArgumentException: No known encodings with chars > 126 (Yours was Ϩ)
	at uk.ac.babraham.FastQC.Sequence.QualityEncoding.PhredEncoding.getFastQEncodingOffset(PhredEncoding.java:48)
	at uk.ac.babraham.FastQC.Modules.PerTileQualityScores.getPercentages(PerTileQualityScores.java:79)
	at uk.ac.babraham.FastQC.Modules.PerTileQualityScores.raisesError(PerTileQualityScores.java:309)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:336)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:185)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:123)
	at java.lang.Thread.run(Thread.java:745)
```

I used Ctuadapt 2.10 and FastQC 0.11.9 installed through conda as well as several other older version of both tools and I still get this error. I could not find any strange characters in the fastq file, moreover, when I split the fastq file so that each read is in the own file (using just `split -l 4`), FastQC works for all of them. Several reads in the fastq files after adapter trimming by Cutadapt are empty, but in the past FastQC never had issues with this. From the same sequencing batch of 24 samples, 2 samples get this error. 

Any idea of what is wrong is greatly appreciated!
Karolína

[METSEQ-P16_SE.ad3short.fastq.zip](https://github.com/s-andrews/FastQC/files/5136143/METSEQ-P16_SE.ad3short.fastq.zip)

**Comment by s-andrews** [comment] 2020-09-01 09:03
Hi Karolína,

Thanks for reporting this and providing the data to reproduce it.

What I think is going on here is a bug in the way fastqc figures out the Phred encoding used in the file.  For the per-tile plot it uses the data in the first tile to get the range of quality scores which it then uses to calculate the Phred scores.

In your file, although there are sequences in the first tile they all have zero length, so there aren't any quality values to use.  For some reason I can't now fathom the default quality value which is returned if there aren't any quality values is 1000, which isn't a valid character and which triggers the error you see.

So there are a few mad things in the code which need to be sorted to fix this.

1. We shouldn't be re-calculating the encoding in the per-tile plot - we should be able to pull it from the general stats where it will use all of the data so this won't be an issue unless every sequence is blank (and I think we test for that already).

2. Having a default min quality of 1000 makes no sense.  We should be triggering a more relevant error rather then returning a random number.

3. The error message itself isn't all that helpful so I'll also add in the chr value to the error so I don't have to spend 10 mins working out that the thing which looks like a number 8 is actually a coptic capital letter 'hori'!

I'll get on and fix these and will update this as I go so we can get this working on this file.

**Comment by trachtok** [comment] 2020-09-02 08:08
Hi Simon,

I am aware that this is probably an issue most of the people will not encounter since the input data are quite specific so thank you for looking into it!

Karolina

**Comment by s-andrews** [comment] 2020-09-02 09:24
I think I've now fixed this with the patch above.  I've put up a development snapshot with the fix in at:

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/FastQC_devel.zip

It's just uploading now so should be there in the next 10 mins.  If you could try that version to confirm that it works for you then I'll add this to the next release.

**Closed** 2020-09-30 09:45 UTC
