### ISSUE TITLE
"java.lang.OutOfMemoryError: Java heap space" with FastQC v0.11.9

### ISSUE THREAD

**Issue by rzelle-lallemand** [s-andrews/FastQC#86] opened 2022-01-22 04:52 UTC
I have a 1 GB PacBio Sequel II CLR FASTQ file (converted from BAM) for which FastQC v0.11.9 hangs on CentOS 7:

```
$ fastqc file.fastq.gz 
Started analysis of file.fastq.gz
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
	at uk.ac.babraham.FastQC.Utilities.QualityCount.<init>(QualityCount.java:33)
	at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.processSequence(PerBaseQualityScores.java:141)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:89)
	at java.lang.Thread.run(Thread.java:745)
```

Command with `-t 2` gives the same result, and with `-t 4` I get a little further but still end up in an OutOfMemoryError hang:

```
$ fastqc file.fastq.gz -t 4
Started analysis of file.fastq.gz
Approx 5% complete for file.fastq.gz
Exception in thread "Thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at uk.ac.babraham.FastQC.Modules.GCModel.GCModel.<init>(GCModel.java:69)
	at uk.ac.babraham.FastQC.Modules.PerSequenceGCContent.processSequence(PerSequenceGCContent.java:198)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:89)
	at java.lang.Thread.run(Thread.java:745)
```

As with #74, would it be possible for FastQC to fail with an error instead of getting stuck? Please let me know if I can help troubleshoot the error. Thanks!

**Comment by s-andrews** [comment] 2022-01-24 08:49
I'll take a look and see what I can do.  The problem here is that when the child process gets killed it doesn't do a standard signal back to the parent to say that it's exited, so it keeps waiting for it.  We have put a number of traps in place to catch errors in the processing of different files, but it seems that the way that OOM failures happen evade these.  I'll see if I can find a way to work round this.

**Comment by s-andrews** [comment] 2022-01-24 08:51
Just to check - we did add an extra error handler based on #74 in v0.11.9.  Can you confirm you're using the latest version and still seeing this?

**Comment by s-andrews** [comment] 2022-01-24 09:20
I just checked and this did seem to do the right thing.  I made a fastq file with a single sequence containing 100million bases then tried to process it:

```
$ fastqc big.fastq
Ran out of memory for big.fastq
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Unknown Source)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.base/java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.base/java.lang.StringBuilder.append(Unknown Source)
        at java.base/java.io.BufferedReader.readLine(Unknown Source)
        at java.base/java.io.BufferedReader.readLine(Unknown Source)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:166)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.<init>(FastQFile.java:89)
        at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:106)
        at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:159)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:121)
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)

$ echo $?
2

$ fastqc -v
FastQC v0.11.9

```

So fastqc immediately exited, and exited with a non-zero status, which all looks like the right thing to do.  Can you check your version as you may just be using an older release.

**Comment by s-andrews** [comment] 2022-01-24 09:21
I can see your error is different in that it's a GC overload rather than a straight memory allocation fail, but I'd have thought it should still be caught the same way.

**Comment by rzelle-lallemand** [comment] 2022-01-24 14:18
One more bit of info: bumping up the thread count to 24 allowed the analysis to finish. Still got a failure with 8.

**Comment by rzelle-lallemand** [comment] 2022-01-24 14:20
> Can you confirm you're using the latest version and still seeing this?

Yes, this is all with v0.11.9.

```
$ fastqc --version
FastQC v0.11.9
```

**Comment by rsmeral** [comment] 2022-05-18 07:15
We're seeing the same problem with v0.11.9 – both, the OOM for some FASTQ files, and also FastQC getting stuck and not exiting after an OOME.

```
...
Approx 90% complete for merged.fastq
Approx 95% complete for merged.fastq
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
```

**Comment by s-andrews** [comment] 2022-05-18 07:23
Can you try running it with the ```-t 2``` option and see if that allows it to complete.

**Comment by rsmeral** [comment] 2022-05-18 07:42
With higher `-t` values, it worked.

However, the hang on OOME is more problematic, we don't want to block our HPC nodes by a hanging process.
My understanding is this could be resolved by the `-XX:+ExitOnOutOfMemoryError` flag (see e.g. https://docs.oracle.com/cd/E15289_01/JRCLR/optionxx.htm#BABCDAIB).

Even though setting higher `-t` value works, it feels like a hack, especially when we're only running a single file where higher number of threads has no effect on speedup.

Also, I see these memory issues are not new, and appear for others too. Just to list a few:
* https://github.com/s-andrews/FastQC/issues/75
* https://github.com/s-andrews/FastQC/issues/88
* http://asearchforsolutions.blogspot.com/2019/04/fastqc-javalangoutofmemoryerror-java.html
* http://seqanswers.com/forums/showthread.php?t=4846&page=16
* https://www.biostars.org/p/193244/

Would you consider either:
* making the `fastqc` wrapper respect the fairly common `JAVA_OPTS` env var, letting people work around these issues
* extending the pattern here to `/^\-D|^\-X/`, to allow for `-Xmx`, `-XX:+ExitOnOutOfMemoryError`, or other custom JVM options to be set: https://github.com/s-andrews/FastQC/blob/master/fastqc#L293
* introducing an option similar to the one suggested here: https://github.com/s-andrews/FastQC/pull/76
* increasing the default 250 MB/thread as you suggested here: https://github.com/s-andrews/FastQC/issues/75#issuecomment-810844208

I'd be happy to make a PR for any of these, if you agreed.

**Comment by s-andrews** [comment] 2022-05-19 14:54
I agree on all of these points.  It's difficult to always do the right thing on the memory allocation since we don't know offhand exactly how much we need until we read the data, at which point its too late.  The biggest issue is with nanopore / pacbio where the read lengths are super long but we have a ```--nano``` flag for those.  We can probably just be a bit more generous in allocating the default which should offset most other problems - we've not see OOM failures from our own internal pipelines from Illumina data. 

I hadn't see that JRE flag but that certainly looks like it would be a useful addition.

I'll have some spare time (for once!) over the next couple of weeks so I'll see how many of the outstanding feature requests I can get through and try to get a new version out which addresses things.

**Comment by rsmeral** [comment] 2022-05-19 22:48
Thank you for dedicating your time.

A few more observations:
* We actually realized the particular OOME occurred because one of our FASTQ files was corrupt – the last 60 MB of the file was just null bytes (`0x00`) instead of actual data. The corruption started in the middle of a quality line. Maybe a potential improvement for later – more robust FASTQ parsing to catch such abnormalities.
* We've tried `-XX:+ExitOnOutOfMemoryError` on OpenJDK 11 and it worked, the JVM exited on OOME. However, it being a `-XX` option, it's not guaranteed (though likely) to be present in all JVMs.

**Comment by rsmeral** [comment] 2022-05-23 09:37
This is a redacted version of the corrupt file, that reproduces the error:
[corrupt-file.fastq.gz](https://github.com/s-andrews/FastQC/files/8753377/corrupt-file.fastq.gz)

It's 59 KB gzipped, expands to 59 MB fastq, and triggers an immediate `java.lang.OutOfMemoryError: Java heap space` for me.

The file is basically a sequence, with a quality line cut off short and followed by null bytes:
```
@1
ATGCATGCATGCATGCATGC
+
BBAABF<59 MB of null bytes start here>
```

**Comment by s-andrews** [comment] 2022-05-23 09:39
Brilliant - thanks!

**Closed** 2022-06-08 07:33 UTC

**Comment by rmzelle** [comment] 2022-06-08 13:17
@s-andrews, thanks so much for the changes. Will there be a new FastQC release soon that incorporates these changes?

**Comment by amizeranschi** [comment] 2023-02-27 05:59
> Can you try running it with the `-t 2` option and see if that allows it to complete.

I'm running into a similar `java.lang.OutOfMemoryError` with FastQC v0.11.9. Running with the `-t 2` option got things working properly, for whatever reason. The input data is a FASTQ file with MinION long reads. Nothing too special about it, as far as I could tell.

**Comment by s-andrews** [comment] 2023-03-01 15:45
FastQC v0.12.1 is now out which should fix most of these memory related issues by increasing the default memory allocation.  If there are still files which generate memory errors then there's now an option (--memory) where you can specifically increase the memory allocation without having to mess around with the number of threads to use.

**Comment by jpeasari** [comment] 2024-10-31 16:16
> Can you try running it with the `-t 2` option and see if that allows it to complete.

-t 2 worked. Thanks.

**Comment by s-andrews** [comment] 2024-11-01 08:46
For future reference if you're using the latest release there is now a better ```--mem``` option which specifically increases the memory allocation and is a better idea than using ```-t``` as it will also work properly if you're processing multiple files
